name: Test on push

on:
  push:
    branches:
      - main
      - integration
    paths:
      - src/**

env:
  SLACK_CHANNEL: C040XHV7E0P

jobs:
  test_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true

      - name: Sync dependencies
        run: rye sync

      - name: Test
        run: rye run pytest --ignore 'tests/test_config.py' tests

      - name: Send Slack message on failure
        uses: someimportantcompany/github-actions-slack-message@v1
        if: failure()
        with:
          channel: ${{ env.SLACK_CHANNEL }}
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          text: Test[s] failed
          color: failure
