name: Unit tests

on:
  workflow_dispatch:

  push:
    branches:
      - integration
    paths:
      - src/**
      - tests/**
      - pyproject.toml

  pull_request:
    branches:
      - main
    paths:
      - src/**
      - tests/**
      - pyproject.toml
jobs:
  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Sync
        run: uv sync

      - name: Library Tests
        run: uv run pytest tests

      - name: CVs Tests branch esgvoc_dev
        run: |
          uv run esgvoc test run cmip7      --branch esgvoc_dev --universe-branch esgvoc_dev
          uv run esgvoc test run cmip6plus  --branch esgvoc_dev --universe-branch esgvoc_dev
          uv run esgvoc test run cmip6      --branch esgvoc_dev --universe-branch esgvoc_dev
          uv run esgvoc test run input4mips --branch esgvoc_dev --universe-branch esgvoc_dev
          uv run esgvoc test run obs4ref    --branch esgvoc_dev --universe-branch esgvoc_dev
          uv run esgvoc test run cordex-cmip6 --branch esgvoc_dev --universe-branch esgvoc_dev
          uv run esgvoc test run cordex-cmip5 --branch esgvoc_dev --universe-branch esgvoc_dev
          uv run esgvoc test run emd        --branch esgvoc_dev --universe-branch esgvoc_dev
