name: Unit tests

on:
  workflow_dispatch:

  push:
    branches:
      - integration
    paths:
      - src/**
      - tests/**
      - pyproject.toml

  pull_request:
    branches:
      - main
    paths:
      - src/**
      - tests/**
      - pyproject.toml

jobs:
  library_tests:
    name: Library tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Sync
        run: uv sync

      - name: Library Tests
        run: uv run pytest tests

  cv_tests:
    name: CV ${{ matrix.project }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - cmip7
          - cmip6plus
          - cmip6
          - input4mips
          - obs4ref
          - cordex-cmip6
          - cordex-cmip5
          - emd
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Sync
        run: uv sync

      - name: Test ${{ matrix.project }}
        run: uv run esgvoc test run ${{ matrix.project }} --branch esgvoc_dev --universe-branch esgvoc_dev
